# Generated by Django 5.0 on 2024-01-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medcine',
            name='user',
        ),
    ]
